#' read Batscope export
#' 
#' reads the \code{xlsx} generated by the batscope export
#'
#' @param path filename
#' @family data functions
#' @export
readBatscopeXLSX <- function(path,quality_threshold){
    rohdaten <- read.xlsx(file_name, sheet = 1, 
        startRow = 1, colNames = TRUE, 
        skipEmptyRows = TRUE, rowNames = FALSE, 
        detectDates = FALSE, rows = NULL, cols = NULL)
    dateOrigin <- getDateOrigin(file_name)
    #str(rohdaten)

    # MODIFY DATA for use in R
    daten <- rohdaten

    # discard sequences with low quality
    dim_qual_before <- dim(rohdaten)
    daten <- dsubset(daten,AutoClass1Qual>quality_threshold)
    dim_qual_after <- dim(daten)
    dim_qual_diff <- dim_qual_before[1]-dim_qual_after[1]

    cat("Discarded ",dim_qual_diff," of ",
        dim_qual_before[1]," sequences (",
        (dim_qual_diff/dim_qual_before[1])*100,"%); ",dim_qual_after[1],
        " remaining\n",sep="")

    str(daten)
    # convert data/time format from excel to R
    daten$ImportDate <- convertToDateTime(rohdaten$ImportDate, 
        origin = dateOrigin)
    #fix subtle difference in POSIXct representation that messes with 
    #some functions
    daten$ImportDate <- as.POSIXct(as.character(daten$ImportDate)) 
    
    daten$SurveyDate <- convertToDateTime(rohdaten$SurveyDate, 
        origin = dateOrigin)
    #fix, see above
    daten$SurveyDate <- as.POSIXct(as.character(daten$SurveyDate)) 
    
    daten$recDate <- convertToDateTime(rohdaten$recDate, origin = dateOrigin)
    #fix, see above
    daten$recDate <- as.POSIXct(as.character(daten$recDate)) 

    daten$recTime <- convertToDateTime(rohdaten$recTime+rohdaten$recDate, 
        origin = dateOrigin)
    #fix, see above
    daten$recTime <- as.POSIXct(as.character(daten$recTime)) 

    # extract microphone position ("Limmattal","See","Uetliberg","Waidberg") 
    # from ProjectName
    daten$micPos <- daten$ProjectName

    # convert chr to factor for easier handling in R
    daten$species <- factor(daten$species)

    return(daten)
}