#' Night Plot
#' 
#' Plot activity (number of calls) over one night.
#'
#' @param plotData data generated by \link{\code{sumBatscopeData}}
#' @param day day to plot in POSIXct format or "YYYY-MM-DD"
#' @param sel_species species_name or vector of species to plot, use "every" to 
#'  plot all species individually (differentiated by color)
#' @param x_limits x-axis limits, NULL (default) or a POSIXct vector of length 2 
#' @param y_limits y-axis limits, NULL (default) or a numeric vector of length 2 
#' @return a \code{ggplot} object
#' @family plot functions
#' @export
night_plot <- function(plotData, 
  day=unique(plotData$SurveyDate)[1],
  sel_species="every",
  x_limits=NULL,
  y_limits=NULL){

  if(is.POSIXct(day)==FALSE){
    day <- as.POSIXct(day,format="%Y-%m-%d")
  }
  
  if(sel_species=="every"){
    plotData_sub <- subset(plotData,SurveyDate==day & species!="all")
  } else {
    plotData_sub <- subset(plotData,SurveyDate==day & 
      species %in% sel_species)
  }

  if(is.null(x_limits)){
    x_limits <- c(plotData_sub$sunset[1]-0.5*3600,
      plotData_sub$sunrise[1]+0.5*3600)
  }
  
  if(is.null(y_limits)){
    y_limits <- c(0,max(plotData_sub$n_events))
  }

  nightPlot <- ggplot(plotData_sub,aes(bins,n_events,fill=species))+
    facet_wrap(~ProjectName)+
    geom_bar(stat="identity",position="dodge",width=300)+
    geom_vline(aes(xintercept=as.numeric(sunset[1])),
      colour="orange")+
    geom_vline(aes(xintercept=as.numeric(sunrise[1])),
      colour="orange")+
    scale_x_datetime(limits=x_limits, breaks=date_breaks("2 hour"),
      minor_breaks=date_breaks("1 hour"),
      labels = date_format("%H:%M"))+
    scale_y_continuous(limits=y_limits)+
    labs(x="Uhrzeit",y="Aktivität (# Events)",title=day)

  return(nightPlot)
  }

#' Period Plot
#' 
#' Plot activity (number of calls) of each night of a given period.
#'
#' @param plotData data generated by \link{\code{sumBatscopeData}}
#' @param start_date in POSIXct format or "YYYY-MM-DD", defaults to the beginning
#'  of the year in which the first data were aquired.
#' @param end_date in POSIXct format or "YYYY-MM-DD", defaults to the end
#'  of the year in which the last data were aquired.
#' @param sel_species species_name or vector of species to plot, use "every" to 
#'  plot all species individually (differentiated by color)
#' @param x_limits x-axis limits, NULL (default) or a POSIXct vector of length 2 
#' @param y_limits y-axis limits, NULL (default) or a numeric vector of length 2 
#' @return a \code{ggplot} object
#' @family plot functions
#' @export
period_plot <- function(plotData, 
  start_date=floor_date(min(plotData$SurveyDate),"year"),
  end_date=ceiling_date(max(plotData$SurveyDate),"year"),
  sel_species="every",
  x_limits=NULL,
  y_limits=NULL){

  if(is.POSIXct(start_date)==FALSE){
    start_date <- as.POSIXct(start_date,format="%Y-%m-%d")
  }
  if(is.POSIXct(end_date)==FALSE){
    start_date <- as.POSIXct(start_date,format="%Y-%m-%d")
  }
  cat("Plotting number of sequences over period:\n")
  print(new_interval(start_date, end_date))
  if(sel_species=="every"){
    plotData_sub <- subset(plotData,
      SurveyDate %within% new_interval(start_date, end_date) &
      species!="all")
    plottitle <- "Summe aller Species"
  } else {
    plotData_sub <- subset(plotData,
      SurveyDate %within% new_interval(start_date, end_date) & 
      species %in% sel_species)
    plottitle <- str_c(sel_species)
  }

  if(is.null(x_limits)){
    x_limits <- c(start_date,end_date)
  }
  
  period_nights <- seq(start_date,end_date,by="days")
  gps_coords <- ddply(plotData_sub,.(ProjectName),summarize,
    lat=lat[1],long=long[1])

  sun_data <- ddply(gps_coords,.(ProjectName),cbind,period_nights)
  names(sun_data)[4] <- "SurveyDate"

  gps_matrix <- matrix(c(sun_data$long,sun_data$lat),ncol=2)
  sun_data$sunset <- sunriset(
      gps_matrix,sun_data$SurveyDate,
       direction="sunset", POSIXct.out=TRUE)[,2]
  sun_data$sunrise <- sunriset(
      gps_matrix,sun_data$SurveyDate+24*60*60,
       direction="sunrise", POSIXct.out=TRUE)[,2]

  plotData_final <- merge(plotData_sub,sun_data,all=TRUE)
  plotData_final$time <- timeOfNight(plotData_final$bins)
  plotData_final$sunrise_time <- timeOfNight(plotData_final$sunrise)
  plotData_final$sunset_time <- timeOfNight(plotData_final$sunset)

  periodPlot <- ggplot(plotData_final,aes(SurveyDate,time))+
    geom_line(aes(SurveyDate,sunrise_time),
      size=0.3,color="grey25")+
    geom_line(aes(SurveyDate,sunset_time),
      size=0.3,color="grey25")+
    facet_wrap(~ProjectName)+
    geom_point(aes(size=n_events),alpha=0.5,color="blue")+
    scale_x_datetime(limits=x_limits,breaks=date_breaks("months"))+
    scale_y_datetime(limits=y_limits,breaks=date_breaks("2 hour"),
      minor_breaks=date_breaks("1 hour"),
      labels = date_format("%H:%M"))+
    labs(x="Datum",y="Uhrzeit [UTC+1]",title=plottitle)+
    theme_bw()

  return(periodPlot)
}