#' Night Plot
#' 
#' Plot activity (number of calls) over one night.
#'
#' @param plotData data generated by 
#' @family plot functions
#' @export
night_plot <- function(plotData){
        nightPlot <- ggplot(plotData,aes(bins,n_events,fill=species))+
            facet_wrap(~micPos)+
            geom_bar(stat="identity",position="dodge",width=300)+
            geom_vline(aes(xintercept=as.numeric(sunset.time[1])),
                colour="orange")+
            geom_vline(aes(xintercept=as.numeric(sunrise.time[1])),
                colour="orange")+
            scale_x_datetime(limits=c(plotData$sunset.time[1]-0.5*3600,
                plotData$sunrise.time[1]+0.5*3600))+
            labs(x="Uhrzeit",y="Aktivität (# Events)",title=plotData$night[1])+
            theme_light()

        return(nightPlot)
    }
#' Year Plot
#' 
#' Plot activity (number of calls) over one night for every data point.
#'
#' @param plotData data generated by 
#' @family plot functions
#' @export
year_plot <- function(plotData,sunriseData,sunsetData){
        yearPlot <- ggplot(plotData,aes(as.Date(night),timeOfNight_utc))+
            geom_line(data=SR_night,mapping=aes(night,sunrise.ton_utc),
                size=0.3,color="grey25")+
            geom_line(data=SS_night,mapping=aes(night,sunset.ton_utc),
                size=0.3,color="grey25")+
            facet_wrap(~micPos)+
            geom_point(aes(size=n_events),alpha=0.5,color="blue")+
            scale_x_date(limits=as.Date(c("2014-01-01","2015-01-01")))+
            labs(x="Datum",y="Uhrzeit [UTC+1]",title=plotData$species[1])+
            theme_light()
        return(yearPlot)
    }

#' Year Plot
#' 
#' Plot activity (number of calls) over one night for every data point.
#'
#' @param plotData data generated by 
#' @family plot functions
#' @export
year_plot_all <- function(plotData,sunriseData,sunsetData){
    yearPlot <- ggplot(plotData,aes(as.Date(night),timeOfNight_utc,color=species))+
        geom_line(data=SR_night,mapping=aes(night,sunrise.ton_utc),
            size=0.3,color="grey25")+
        geom_line(data=SS_night,mapping=aes(night,sunset.ton_utc),
            size=0.3,color="grey25")+
        facet_wrap(~micPos)+
        geom_point(aes(size=log10(n_events)),alpha=0.5)+
        scale_x_date(limits=as.Date(c("2014-01-01","2015-01-01")))+
        labs(x="Datum",y="Uhrzeit [UTC+1]",title=plotData$species[1])+
        theme_light()
    return(yearPlot)
}